// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfY98D-peXtw864EPsJZ5c5GKFzNTqjjg',
    appId: '1:57396923024:web:45d1aee3470b40381ae615',
    messagingSenderId: '57396923024',
    projectId: 'creamy-ice-f9967',
    authDomain: 'creamy-ice-f9967.firebaseapp.com',
    storageBucket: 'creamy-ice-f9967.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsO68-xsy0yz09ldIvmVNWU3KxCRrAReQ',
    appId: '1:57396923024:android:93803b9ed970e8c71ae615',
    messagingSenderId: '57396923024',
    projectId: 'creamy-ice-f9967',
    storageBucket: 'creamy-ice-f9967.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi2Mlp-xusxcXtMQCZRyf8evFlyIsSAuY',
    appId: '1:57396923024:ios:1035ca78bbad23f41ae615',
    messagingSenderId: '57396923024',
    projectId: 'creamy-ice-f9967',
    storageBucket: 'creamy-ice-f9967.appspot.com',
    iosBundleId: 'com.example.creamyice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi2Mlp-xusxcXtMQCZRyf8evFlyIsSAuY',
    appId: '1:57396923024:ios:ede2b80b5936b9131ae615',
    messagingSenderId: '57396923024',
    projectId: 'creamy-ice-f9967',
    storageBucket: 'creamy-ice-f9967.appspot.com',
    iosBundleId: 'com.example.creamyice.RunnerTests',
  );
}
